# Generated by Django 3.2.4 on 2021-06-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='username')),
                ('fullname', models.CharField(max_length=255)),
                ('phonenumber', models.CharField(blank=True, max_length=15)),
                ('addressId', models.IntegerField(blank=True, default=0)),
                ('addressName', models.CharField(blank=True, default='T.P Hồ Chí Minh', max_length=255)),
                ('gender', models.CharField(blank=True, default='another', max_length=10)),
                ('hieght', models.IntegerField(blank=True, default=170, verbose_name='Chiều cao (cm)')),
                ('hobbies', models.CharField(blank=True, default='', max_length=255)),
                ('image', models.ImageField(blank=True, default='/images/default.jpg', upload_to='images')),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
