# Generated by Django 3.2.4 on 2021-06-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_hieght_user_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.DateField(blank=True, default='1999-08-09'),
        ),
    ]
