# Generated by Django 3.2.4 on 2021-06-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0004_chatroom_view_users'),
        ('users', '0004_user_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='room_chat',
            field=models.ManyToManyField(blank=True, help_text='user thuoc chatroom', to='Web.ChatRoom'),
        ),
    ]
