# Generated by Django 3.2.4 on 2021-06-23 07:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='user thuoc chatroom', to=settings.AUTH_USER_MODEL),
        ),
    ]
