# Generated by Django 3.2.4 on 2021-06-24 08:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Web', '0003_waitingroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='view_users',
            field=models.ManyToManyField(blank=True, help_text='user only view', related_name='Viewer', to=settings.AUTH_USER_MODEL),
        ),
    ]
